name: Docker build image proxy

on:
  push:
    branches: [ "testing", "self-host-updates" ]
    paths:
      - "imageproxy/**"
  pull_request:
    branches: [ "self-host-updates" ]

jobs:
  build-image:
    uses: ./.github/workflows/docker-build-push.yaml
    with:
      image-name: omnivore-image-proxy
      context: ./imageproxy
      dockerfile-path: ./imageproxy/Dockerfile