name: Docker build content-fetch

on:
  push:
    branches: [ "testing", "self-host-updates" ]
    paths:
      - "packages/web/**"
  pull_request:
    branches: [ "self-host-updates" ]
  workflow_dispatch:
jobs:
  build-image:
    uses: ./.github/workflows/docker-build-push.yaml
    with:
      image-name: omnivore-web
      dockerfile-path: ./packages/web/Dockerfile
      build-args: |
        - APP_ENV=prod
        - BASE_URL=https://omnivore.m1xxos.me
        - SERVER_BASE_URL=https://omnivore.m1xxos.me
        - HIGHLIGHTS_BASE_URL=https://omnivore.m1xxos.me
        - USE_NATIVE_PDF=true